# Generated by Django 3.1.5 on 2021-01-22 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=2000)),
                ('MessagePartner', models.CharField(max_length=2000)),
                ('UnreadMessages', models.BooleanField(default=False)),
            ],
        ),
    ]
