# Generated by Django 3.1.5 on 2021-01-26 06:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_logos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmessages',
            name='Messages',
            field=models.ManyToManyField(blank=True, to='main.Messages'),
        ),
        migrations.AlterField(
            model_name='messagebox',
            name='UnreadMessages',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='plans',
            name='PlanServices',
            field=models.ManyToManyField(blank=True, to='main.Service'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Service',
            field=models.ManyToManyField(blank=True, to='main.Service'),
        ),
        migrations.AlterField(
            model_name='service',
            name='RatedBy',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='service',
            name='ServiceFeedback',
            field=models.ManyToManyField(blank=True, to='main.ServiceFeedback'),
        ),
        migrations.AlterField(
            model_name='service',
            name='ServiceImages',
            field=models.ManyToManyField(blank=True, to='main.Images'),
        ),
    ]
