# Generated by Django 3.1.5 on 2021-01-26 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210126_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='MobileNo',
            field=models.CharField(max_length=20),
        ),
    ]
