# Generated by Django 3.1.5 on 2021-01-28 04:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0005_auto_20210126_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.images'),
        ),
        migrations.AlterField(
            model_name='feedbacks',
            name='Image',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.images'),
        ),
        migrations.CreateModel(
            name='USerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.images')),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
