# Generated by Django 3.1.5 on 2021-02-01 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210128_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frontpagefeedback',
            name='Type',
            field=models.CharField(default='Normal', max_length=100),
        ),
        migrations.AlterField(
            model_name='service',
            name='SearchNames',
            field=models.ManyToManyField(blank=True, to='main.SearchName'),
        ),
        migrations.AlterField(
            model_name='service',
            name='Type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.servicescatagory'),
        ),
    ]
