# Generated by Django 3.1.5 on 2021-02-04 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20210201_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='Rating',
            field=models.FloatField(default=3),
        ),
    ]
