# Generated by Django 3.1.5 on 2021-02-17 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20210204_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='Description',
            field=models.TextField(default='Description box is empty.'),
        ),
    ]
