# Generated by Django 3.1.5 on 2021-02-17 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_service_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='InterestedServices',
            field=models.ManyToManyField(blank=True, to='main.Service'),
        ),
    ]
