# Generated by Django 3.1.5 on 2021-02-17 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_userprofile_interestedservices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='InterestedServices',
        ),
    ]
