# Generated by Django 3.1.5 on 2021-03-16 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_service_vstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='Address',
            field=models.TextField(default='0'),
        ),
        migrations.AddField(
            model_name='service',
            name='lat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='service',
            name='lng',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
