# Generated by Django 3.1.5 on 2021-03-16 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20210316_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='lat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='lng',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='lat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='lng',
            field=models.FloatField(default=0),
        ),
    ]
