# Generated by Django 3.1.5 on 2021-03-26 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20210316_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostCommentsReplies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=1000)),
                ('Reply', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TotalHits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hits', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TotalHitsPerPersonPerDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=1000)),
                ('Hits', models.IntegerField()),
                ('Date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='LastCategory',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.servicescatagory'),
        ),
        migrations.AddField(
            model_name='profile',
            name='LastProduct',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='LastProduct+', to='main.service'),
        ),
        migrations.AddField(
            model_name='profile',
            name='LastSearchNotFound',
            field=models.TextField(default='RENTYUG'),
        ),
        migrations.AddField(
            model_name='profile',
            name='LastSearcheTag',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.searchname'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='LastCategory',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.servicescatagory'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='LastProduct',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.service'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='LastSearchNotFound',
            field=models.TextField(default='RENTYUG'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='LastSearcheTag',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.searchname'),
        ),
        migrations.CreateModel(
            name='PostComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=1000)),
                ('Comment', models.TextField()),
                ('Replies', models.ManyToManyField(blank=True, to='main.PostCommentsReplies')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tittle', models.TextField()),
                ('Media', models.FileField(blank=True, upload_to='')),
                ('Text', models.TextField()),
                ('TotalLikes', models.IntegerField(default=0)),
                ('Comments', models.ManyToManyField(blank=True, to='main.PostComments')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='LikedPosts',
            field=models.ManyToManyField(blank=True, related_name='_profile_LikedPosts_+', to='main.Post'),
        ),
        migrations.AddField(
            model_name='profile',
            name='SavedPosts',
            field=models.ManyToManyField(blank=True, related_name='_profile_SavedPosts_+', to='main.Post'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='LikedPosts',
            field=models.ManyToManyField(blank=True, related_name='_userprofile_LikedPosts_+', to='main.Post'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='SavedPosts',
            field=models.ManyToManyField(blank=True, related_name='_userprofile_SavedPosts_+', to='main.Post'),
        ),
    ]
