# Generated by Django 3.1.5 on 2021-03-26 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20210326_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='Posts',
            field=models.ManyToManyField(blank=True, to='main.Post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='Media',
            field=models.FileField(blank=True, upload_to='Posts'),
        ),
    ]
