# Generated by Django 3.1.5 on 2021-03-26 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20210326_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totalhits',
            name='Hits',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='totalhitsperpersonperday',
            name='Date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='totalhitsperpersonperday',
            name='Hits',
            field=models.IntegerField(default=0),
        ),
    ]
