# Generated by Django 3.1.5 on 2021-03-26 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20210326_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='LastSearcheTag',
            field=models.TextField(default='RENTYUG'),
        ),
    ]
