# Generated by Django 3.1.5 on 2021-03-27 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20210326_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Activated',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='service',
            name='Activated',
            field=models.BooleanField(default=True),
        ),
    ]
