# Generated by Django 3.1.5 on 2021-03-27 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_auto_20210327_0810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='LastProduct',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='LastProduct',
        ),
        migrations.AddField(
            model_name='profile',
            name='LastProductTags',
            field=models.ManyToManyField(blank=True, to='main.SearchName'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='LastProductTags',
            field=models.ManyToManyField(blank=True, to='main.SearchName'),
        ),
    ]
