# Generated by Django 3.1.5 on 2021-03-28 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_post_likedby'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='LikedPosts',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='LikedPosts',
        ),
    ]
