# Generated by Django 3.1.5 on 2021-03-29 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_auto_20210328_0711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='LastCategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.servicescatagory'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='LastCategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.servicescatagory'),
        ),
    ]
