# Generated by Django 3.1.5 on 2021-03-29 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_auto_20210329_1023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='SavedPosts',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='SavedPosts',
        ),
        migrations.AddField(
            model_name='profile',
            name='SavedServices',
            field=models.ManyToManyField(blank=True, related_name='_profile_SavedServices_+', to='main.Service'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='SavedServices',
            field=models.ManyToManyField(blank=True, related_name='_userprofile_SavedServices_+', to='main.Service'),
        ),
    ]
