# Generated by Django 3.1.5 on 2021-04-23 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_auto_20210329_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='NoOfItems',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='service',
            name='RentalStatus',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='USerProfile',
        ),
    ]
